name: Lint Web App
on: [pull_request]
jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        working-directory: ./web
        with:
          node-version: '16'
      - name: Install NPM Dependencies
        run: npm ci
        working-directory: ./web
      - uses: reviewdog/action-eslint@v1
        working-directory: ./web
        with:
          reporter: github-pr-review
