name: Lint Web App
on: [pull_request]
jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-eslint@v1
        with:
          workdir: './web'
          reporter: github-pr-review
