name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          export NVM_DIR="$HOME/.nvm"
          [-s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          bash /home/pi/autoupdater-snake
          ls -al
          echo "$PATH"
